### ISSUE TITLE
Problems syncing Firewall rules with Ubuntu 12.04

### ISSUE THREAD

**Issue by jpgriffo** [ingrammicro/concerto#1]
Seems that in ubuntu 12.04  iptables does not allow for locking mechanisms.

`root@dbecom:/etc/mysql# /sbin/iptables -w -A CONCERTO -s 0.0.0.0/0 -p tcp --dport 3306:3306 -j ACCEPT
`
`iptables v1.4.12: unknown option "-w"`

**Comment by pbanos** [comment]
Closing because we no longer support Ubuntu 12.04
