### ISSUE TITLE
cloud account parameter in wizard app

### ISSUE THREAD

**Issue by fjcoira** [ingrammicro/concerto#7]
In master branch, cloud provider is still used, but Concerto 5.0.0 > uses cloud account as parameter.

This feature has to be updated (wizard/apps/subcommands.go).

**Comment by fjcoira** [comment]
Also, it should provide a new command "cloud_accounts" (instead of wizard/cloud_providers/subcommands.go).

**Comment by pbanos** [comment]
Duplicate of #3
