### ISSUE TITLE
Script execution must use the new index route and then download URLs for each attachment to obtain them

### ISSUE THREAD

**Issue by lttito** [ingrammicro/concerto#87]
# Expected Behavior
On script execution, for CLI to get each attachment files, it must get all attachments from script calling index, then for each attachment it should download the file from download_url contained in response

# Current Behavior
CLI calls once for each attachment to get its file. 

# Possible Solution
Change CLI code

# Steps to Reproduce (for bugs)

    1.
    2.
    3.
    4.

# Context and environment

**Comment by pcantera** [comment]
implemented in #91
