### ISSUE TITLE
Bootstrap command to drive chef-zero-based configuration

### ISSUE THREAD

**Issue by pbanos** [ingrammicro/concerto#90]
# Expected Behavior

The tool should have a bootstrap command that starts the following loop that ends only when it receives a TERM signal:
- Inquire about desired configuration changes to be applied by querying the `GET /blueprint/configuration` endpoint. This will provide a JSON response with the desired configuration changes, similar to 
  ```JSON
  {
    "policyfiles": [
       {
          "id": "<id of a template addon>",
          "revision_id": "<revision id of latest compilation>",
          "download_url": "<URL to download the latest compilation>"
       },
       {
          "id": "<id of a template>",
          "revision_id": "<revision id of latest compilation>",
          "download_url": "<URL to download the latest compilation>"
       } 
    ],
    "attributes" : { "arbitrary": {"keys": ["and", {"value": "s"}]}},
    "attribute_revision_id": "<revision id for attributes>"
  }
  ```
- For every policyfile, ensure its tarball (downloadable through their download_url) has been downloaded to the server and clean off any tarball that is no longer needed.
- Store the attributes as JSON in a file with name `attrs-<attribute_revision_id>.json`
- Take the current timestamp for later use as `started_at`
- For every policyfile, apply them doing the following:
  -  Extract the tarball to a temporal work directory DIR
  -  Run  `cd DIR; chef-client -z -j path/to/attrs-<attribute_revision_id>.json` while sending the stderr and stdout in bunches of 10 lines to the platform via `POST /blueprint/bootstrap_logs` (this resource is a copy of POST /command_polling/bootstrap_logs used in the command_polling command). If the command returns with a non-zero value, stop applying policyfiles and continue with the next step.
- ~~On the first iteration that applies successfully all policyfiles (runs all `chef-client -z` commands obtaining 0 return codes) only, run the boot scripts for the server by executing the `scripts boot` sub-command (as an external process).~~
- Inform the platform of applied changes via a `PUT /blueprint/applied_configuration` request with a JSON payload similar to 
  ```JSON
  {
    "started_at": "<JSON serialization of timestamp saved previously>",
    "finished_at": "<JSON serialization of current timestamp>",
    "policyfile_revision_ids": {
      "<id of a template addon>": "<revision id of latest compilation>",
      "<id of a template>": "<revision id of latest compilation>"
    },
    "attribute_revision_id": "<revision id for attributes>"
  }
  ```
  The `policyfile_revision_ids` field should have revision ids set only for those policyfiles successfully applied on the iteration, that is, it should not have any values set for those failing and those skipped because of a previous one failing.
- Sleep for a configured amount of time plus a random amount of time (10 minutes plus 0 to 5 minutes, for instance)

# Current Behavior

# Possible Solution

# Context and environment

**Comment by ptemmer** [comment]
In Windows remote_file resources are failing with "no such file" error.

`No such file or directory @ rb_sysopen - c:/users/admini~1/appdata/local/temp/cio/txi_ewb64gwkbgy53-bef4af9413fb9b6a37166313514b21c74af8f5164e5202fba75c680879eb5c95/.chef/local-mode-cache/cache/remote_file/https___s3_us_west_2_amazonaws_com_storage_imco_io_nssm_2_24_nss-5b0b77093a25261274e88c4bdbccbe99.json`

The reason this is happening is because the actual policyfile directory contains uppercase letters, which are not passed as such in Windows to the Chef's Ruby process, resulting in the above error.

As a workaround we should rename the policyfile directory before launching the chef run, or refrain from using uppercase letters.
